"""Natural OLMo trajectories: passive geometry, topology and native Adam channels.
No optimizer resets or activation patches. See README for measurement boundaries.
"""
from __future__ import annotations
import os
os.environ.setdefault('MPLCONFIGDIR','/tmp/olmo_natural_geometry_mpl')
os.environ.setdefault('CUBLAS_WORKSPACE_CONFIG',':4096:8')
import argparse, copy, csv, gc, hashlib, json, math, platform, shutil, signal
import sqlite3, subprocess, sys, time, traceback, uuid, zipfile
from pathlib import Path
import numpy as np
import torch
from association_core import Config, Engine, make_data, minibatches, collate, digest, load
from geometry_math import points_distance, persistent_homology, entropy_rank
VERSION='natural-geometry-1.0'
SPLITS=['A_valid','B_valid','A_test','B_test']


def atomic_json(obj,path):
    p=Path(path);p.parent.mkdir(parents=True,exist_ok=True)
    q=p.with_name(p.name+'.tmp');q.write_text(json.dumps(obj,indent=2,allow_nan=False));os.replace(q,p)


def read(path,default=None):
    try:return json.loads(Path(path).read_text())
    except FileNotFoundError:return default


def discover_source():
    roots=[Path('/home/ubuntu/1/runs/olmo_association_v1'),Path.cwd()/'runs/olmo_association_v1',Path.home()/'1/runs/olmo_association_v1']
    return next((str(p.resolve()) for p in roots if (p/'config.json').exists() and list(p.glob('seed*/anchor.pt'))),None)


def defaults(source=None,output=None):
    source=source or discover_source()
    if source is None:raise FileNotFoundError('Set SOURCE to the original olmo_association_v1 directory containing config.json and seed*/anchor.pt.')
    c=read(Path(source)/'config.json');seeds=[int(x) for x in c['seeds'] if (Path(source)/f'seed{x}/anchor.pt').exists()]
    return dict(version=VERSION,source=str(Path(source).expanduser().resolve()),
        output=str(Path(output or Path.cwd()/'runs/olmo_natural_geometry_v1').expanduser().resolve()),
        device='cuda:0',threads=8,seeds=seeds,hours=11.5,reserve_minutes=10,
        start_step=0,end_step=min(128,c['b_steps']),chunk_steps=8,checkpoint_every=8,
        geometry_every=4,derivative_every=4,curvature_every=16,curvature_entities=2,
        monitor_entities=8,topology_entities=16,geometry_layers=[],frame_rank=8,
        matrix_sample_rows=32,matrix_sample_cols=256,matrix_nulls=4,topology_nulls=4,
        eval_batch=4,minimum_free_gb=30.,max_measurement_gb=20.,partition_seed=8041)


def validate(s):
    if s.get('version')!=VERSION:raise ValueError('Use settings generated by defaults() from this release.')
    c=Config(**read(Path(s['source'])/'config.json'))
    for k in ['chunk_steps','checkpoint_every','geometry_every','derivative_every','monitor_entities','topology_entities','eval_batch','threads','frame_rank','matrix_sample_rows','matrix_sample_cols']:
        if not isinstance(s[k],int) or s[k]<1:raise ValueError(k+' must be a positive integer')
    if not s['seeds'] or len(set(s['seeds']))!=len(s['seeds']):raise ValueError('Provide distinct available seeds.')
    if not 0<=s['start_step']<s['end_step']<=c.b_steps:raise ValueError(f'Need 0 <= start_step < end_step <= source b_steps ({c.b_steps}).')
    if s['hours']*60<=s['reserve_minutes']:raise ValueError('Time budget must exceed reserve.')
    if s['curvature_every']<0 or s['curvature_entities']<1:raise ValueError('Invalid curvature settings.')
    if s['monitor_entities']+s['topology_entities']>c.entities or s['topology_entities']>32:raise ValueError('Monitor and topology identities must be disjoint; PH supports <=32 landmarks.')
    if not c.smoke and not Path(c.model).exists() and (len(c.revision)!=40 or any(x not in '0123456789abcdef' for x in c.revision.lower())):raise ValueError('Original config must contain its pinned 40-character HF revision. Do not replace it with main.')
    for seed in s['seeds']:
        for f in ['anchor.pt','data.json']:
            if not (Path(s['source'])/f'seed{seed}'/f).exists():raise FileNotFoundError(f'Missing seed{seed}/{f}')
    if c.transition not in ['keep','reset']:raise ValueError('Unknown original transition policy.')
    c.device=s['device'];c.threads=s['threads'];return c


class Pause(Exception):pass
class Control:
    def __init__(self,s):
        self.s=s;self.out=Path(s['output']);self.start=time.time();self.deadline=self.start+s['hours']*3600-s['reserve_minutes']*60
        self.last_check=0;self.phase={};self.last_progress=time.time()
    def pulse(self,**fields):
        self.phase.update(fields);self.last_progress=time.time()
        atomic_json(dict(status='running',last_progress=self.last_progress,**self.phase),self.out/'status.json')
    def check(self):
        if (self.out/'STOP').exists():raise Pause('Stop requested')
        if time.time()>self.deadline:raise Pause('Session time budget reached')
        if shutil.disk_usage(self.out).free<self.s['minimum_free_gb']*1024**3:raise Pause('Disk reserve reached')
    def storage(self):
        size=sum(p.stat().st_size for p in self.out.rglob('*') if p.is_file() and p.suffix not in ['.pt','.tmp'])
        if size>self.s['max_measurement_gb']*1024**3:raise Pause('Measurement storage budget reached; increase max_measurement_gb to resume')


def db_open(out):
    con=sqlite3.connect(Path(out)/'measurements.sqlite',timeout=60)
    con.execute('PRAGMA journal_mode=WAL')
    con.execute('CREATE TABLE IF NOT EXISTS steps(seed INTEGER, step INTEGER, record TEXT NOT NULL, PRIMARY KEY(seed,step))')
    con.commit();return con


def dot(a,b):return float(torch.sum(a.double()*b.double()).item())
def cos(a,b):return dot(a,b)/max(math.sqrt(dot(a,a)*dot(b,b)),1e-30)
def group(name):
    if '.q_proj.' in name or '.k_proj.' in name:return 'QK'
    if '.gate_proj.' in name:return 'gate'
    if '.v_proj.' in name or '.o_proj.' in name:return 'OV'
    if '.up_proj.' in name or '.down_proj.' in name:return 'MLP_content'
    return 'embedding_readout_other'


def mean_gradient(e,rows):
    e.opt.zero_grad(set_to_none=True)
    for i in range(0,len(rows),e.c.microbatch):
        (e.loss_rows(rows[i:i+e.c.microbatch]).sum()/len(rows)).backward()
    result={n:p.grad.detach().cpu().clone() for n,p in e.params.items() if p.grad is not None}
    e.opt.zero_grad(set_to_none=True);return result


def channels(e):
    """Native Adam history/current numerator terms, shared updated denominator.
    Only ordinary Adam with zero weight decay is admitted by the copied engine.
    """
    hist={};cur={}
    for pg in e.opt.param_groups:
        if pg.get('weight_decay',0)!=0 or pg.get('amsgrad',False) or pg.get('maximize',False):raise ValueError('Unsupported optimizer variant; decomposition refused.')
        b1,b2=pg['betas'];lr=pg['lr'];eps=pg['eps']
        for p in pg['params']:
            if p.grad is None:continue
            st=e.opt.state[p];t=int(st['step'].item())+1 if 'step' in st else 1
            m=st.get('exp_avg',torch.zeros_like(p));v=st.get('exp_avg_sq',torch.zeros_like(p))
            den=(b2*v+(1-b2)*p.grad.square()).sqrt()/math.sqrt(1-b2**t)+eps
            fac=-lr/(1-b1**t)
            name=next(n for n,q in e.params.items() if q is p)
            hist[name]=(fac*b1*m/den).detach().cpu()
            cur[name]=(fac*(1-b1)*p.grad/den).detach().cpu()
    return hist,cur


def mixed_curvature(e,rows,h,c):
    """Exact autograd mixed Hessian contraction on a fixed monitor subset.
    Derivatives at unmodified weights; does not perform a virtual optimizer step.
    """
    params=tuple(e.params.values());names=list(e.params);vals=[]
    for row in rows:
        loss=e.loss_rows([row]).mean()
        g=torch.autograd.grad(loss,params,create_graph=True)
        gh=sum((a*h[n].to(a.device)).sum() for n,a in zip(names,g))
        hv=torch.autograd.grad(gh,params,allow_unused=True)
        val=sum(dot(v,c[n].to(v.device)) for n,v in zip(names,hv) if v is not None)
        vals.append(val);del loss,g,gh,hv
    return dict(h_H_c=float(np.mean(vals)),entities=[r['entity'] for r in rows],per_entity=vals,
        convention='Current monitor-subset loss Hessian; history/current use actual shared updated Adam denominator.')


def evaluate(e,data,batch):
    out={}
    with torch.no_grad():
        for split in SPLITS:
            rows=[]
            for i in range(0,len(data[split]),batch):
                rr=data[split][i:i+batch];inp,q,lab=collate(rr,e.tok.pad_token_id,e.c.device)
                h=e.model.model(**inp,use_cache=False,return_dict=True).last_hidden_state[:,-1,:]
                lp=e.model.lm_head(h).double().log_softmax(-1)
                kl=(q*(q.log()-lp[:,lab])).sum(-1);mass=-lp[:,lab].logsumexp(-1);margin=lp[:,lab[0]]-lp[:,lab[1]]
                rows.extend(dict(entity=r['entity'],q0=r['q'][0],loss=float(l),support=float(m),margin=float(z)) for r,l,m,z in zip(rr,kl,mass,margin))
            out[split]=dict(mean=float(np.mean([r['loss'] for r in rows])),rows=rows)
    return out


def split_ids(s,c):
    order=np.random.default_rng(s['partition_seed']).permutation(c.entities).tolist()
    return order[:s['monitor_entities']],order[s['monitor_entities']:s['monitor_entities']+s['topology_entities']]


def fixed_scale(d):
    v=d[np.triu_indices(len(d),1)];v=v[v>1e-12];return float(np.median(v)) if len(v) else 1.


def subspace(x,k):
    x=np.asarray(x,float);u,s,v=np.linalg.svd(x-x.mean(0),full_matrices=False)
    rank=min(k,int(np.sum(s>max(float(s[0]) if len(s) else 0,1e-30)*1e-7)))
    return v[:rank],s


def frame_metrics(x,x0,sens,sens0,rank):
    x=np.asarray(x,float);x0=np.asarray(x0,float);sens=np.asarray(sens,float);sens0=np.asarray(sens0,float)
    b,sv=subspace(x,rank);b0,_=subspace(x0,rank);k=min(len(b),len(b0))
    cs=np.linalg.svd(b[:k]@b0[:k].T,compute_uv=False).clip(0,1) if k else np.array([])
    dx=x-x0;ds=sens-sens0
    dn=np.linalg.norm(dx,axis=1);sn=np.linalg.norm(sens0,axis=1)
    return dict(mean_shift_norm=float(np.linalg.norm(x.mean(0)-x0.mean(0))),mean_row_norm=float(np.linalg.norm(x,axis=1).mean()),
        centered_effective_rank=entropy_rank(sv**2),top_variance_fraction=float(sv[0]**2/max(np.sum(sv**2),1e-30)),
        principal_angles_degrees=np.degrees(np.arccos(cs)).tolist(),subspace_rank_compared=k,
        per_entity_displacement_norm=dn.tolist(),sensitivity_norm=np.linalg.norm(sens,axis=1).tolist(),
        old_sensitivity_dot_displacement=np.einsum('ij,ij->i',sens0,dx).tolist(),
        current_sensitivity_dot_displacement=np.einsum('ij,ij->i',sens,dx).tolist(),
        sensitivity_change_dot_displacement=np.einsum('ij,ij->i',ds,dx).tolist(),
        old_sensitivity_displacement_cosine=(np.einsum('ij,ij->i',sens0,dx)/np.maximum(dn*sn,1e-30)).tolist(),
        spectrum=(sv**2).tolist())


def mst_edges(d,entities,targets):
    n=len(d);used={0};edges=[]
    while len(used)<n:
        dist,i,j=min((float(d[i,j]),i,j) for i in used for j in range(n) if j not in used)
        used.add(j);edges.append(dict(entity1=int(entities[i]),entity2=int(entities[j]),distance=dist,same_target=bool(targets[i]==targets[j])))
    return edges


def topology_record(x,x0,metric,entities,targets,nulls,seed):
    d=points_distance(x);d0=points_distance(x0);scale=fixed_scale(d0)
    task=points_distance(x@metric.T);task0=points_distance(x0@metric.T);ts=fixed_scale(task0)
    ph=persistent_homology(d/scale,[.25,.5,1.,1.5,2.]);tph=persistent_homology(task/ts,[.25,.5,1.,1.5,2.])
    rng=np.random.default_rng(seed);null=[];xc=x-x.mean(0);n=len(x)
    # Orthogonal mixing within the subspace perpendicular to the constant vector.
    basis=np.linalg.svd(np.ones((1,n)),full_matrices=True)[2][1:].T
    for _ in range(nulls):
        q,_=np.linalg.qr(rng.normal(size=(n-1,n-1)));xn=basis@q@basis.T@xc
        p=persistent_homology(points_distance(xn)/scale,[1.])
        null.append(dict(H0=p['H0']['finite_total_persistence'],H1=p['H1']['finite_total_persistence']))
    base_nn=np.argsort(d0,axis=1)[:,1:4];nn=np.argsort(d,axis=1)[:,1:4]
    return dict(PH=ph,task_semimetric_PH=tph,baseline_scale=scale,task_baseline_scale=ts,
        mst=mst_edges(d/scale,entities,targets),neighbor_retention=float(np.mean([len(set(a)&set(b))/len(a) for a,b in zip(nn,base_nn)])),
        spectrum_preserving_point_mixing_null=null,
        note='Frozen monitor margin-gradient map; not Fisher/Hessian. Point-mixing null preserves centered feature covariance, not entity semantics.')


def capture(e,data,s,monitor,held,ctl):
    layers=s['geometry_layers'] or list(range(e.model.config.num_hidden_layers))
    if any(l<0 or l>=e.model.config.num_hidden_layers for l in layers):raise ValueError('Requested geometry layer does not exist.')
    arrays={};meta={}
    for split in SPLITS:
        ids=monitor if split.endswith('valid') else held
        rows=[r for r in data[split] if r['entity'] in ids];meta[split]=dict(entities=[r['entity'] for r in rows],q0=[r['q'][0] for r in rows])
        per={str(l):{'x':[],'lossgrad':[],'margin_grad':[]} for l in layers};per['final']={'x':[],'lossgrad':[],'margin_grad':[]}
        for r in rows:
            ctl.check();ctl.pulse(phase='passive activation/sensitivity capture',split=split,entity=r['entity'])
            taps={};handles=[]
            for l in layers:
                def hook(mod,inp,out,key=str(l)):
                    taps[key]=out[0] if isinstance(out,tuple) else out
                handles.append(e.model.model.layers[l].register_forward_hook(hook))
            try:
                inp,q,labels=collate([r],e.tok.pad_token_id,e.c.device)
                final=e.model.model(**inp,use_cache=False,return_dict=True).last_hidden_state;taps['final']=final
                lp=e.model.lm_head(final[:,-1,:]).double().log_softmax(-1)
                loss=(q*(q.log()-lp[:,labels])).sum();margin=(lp[:,labels[0]]-lp[:,labels[1]]).sum()
                keys=list(taps);targets=[taps[k] for k in keys]
                gl=torch.autograd.grad(loss,targets,retain_graph=True)
                gm=torch.autograd.grad(margin,targets)
                for k,a,b in zip(keys,gl,gm):
                    per[k]['x'].append(taps[k][0,-1].detach().float().cpu().numpy().copy())
                    per[k]['lossgrad'].append(a[0,-1].detach().float().cpu().numpy().copy())
                    per[k]['margin_grad'].append(b[0,-1].detach().float().cpu().numpy().copy())
            finally:
                for h in handles:h.remove()
            del taps,targets,gl,gm,final,lp,loss,margin
        for k,v in per.items():
            for name,vals in v.items():arrays[f'{split}__{k}__{name}']=np.stack(vals).astype(np.float32)
    return arrays,meta


def geometry_analysis(arrays,base,previous,meta,s,seed):
    out={}
    for split,m in meta.items():
        if not split.endswith('test'):continue
        for key in [k for k in arrays if k.startswith(split+'__') and k.endswith('__x')]:
            site=key.split('__')[1];prefix=split+'__'+site+'__';calprefix=split.replace('test','valid')+'__'+site+'__'
            x=arrays[key].astype(float);x0=base[key].astype(float);sens=arrays[prefix+'lossgrad'];sens0=base[prefix+'lossgrad']
            metric=base[calprefix+'margin_grad'].astype(float)/math.sqrt(len(base[calprefix+'margin_grad']))
            entry=dict(anchor=frame_metrics(x,x0,sens,sens0,s['frame_rank']),previous=frame_metrics(x,previous[key],sens,previous[prefix+'lossgrad'],s['frame_rank']),
                topology=topology_record(x,x0,metric,m['entities'],m['q0'],s['topology_nulls'],seed),entities=m['entities'],q0=m['q0'])
            # Held-out Procrustes residual; fitting uses monitor identities only.
            a=arrays[calprefix+'x'].astype(float);b=base[calprefix+'x'].astype(float)
            joint=np.concatenate([a,b],axis=0);_,sv,v=np.linalg.svd(joint,full_matrices=False)
            rank=int(np.sum(sv>max(sv[0],1e-30)*1e-7));basis=v[:rank].T
            u,_,vh=np.linalg.svd((a@basis).T@(b@basis),full_matrices=False);r=u@vh
            aligned=x+(x@basis)@(r-np.eye(rank))@basis.T
            entry['alignment']=dict(native_mse=float(np.mean((x-x0)**2)),heldout_orthogonal_mse=float(np.mean((aligned-x0)**2)),rank=rank,includes_reflections=True)
            out[prefix]=entry
    return out


def sampled_matrices(e,s,seed):
    """Fixed coordinate samples of every unique matrix; not full spectra or MP tests."""
    out={}
    for name,p in e.params.items():
        if p.ndim!=2:continue
        rng=np.random.default_rng(int(hashlib.sha256(name.encode()).hexdigest()[:8],16))
        ri=np.sort(rng.choice(p.shape[0],min(s['matrix_sample_rows'],p.shape[0]),replace=False));ci=np.sort(rng.choice(p.shape[1],min(s['matrix_sample_cols'],p.shape[1]),replace=False))
        a=p.detach()[torch.as_tensor(ri,device=p.device)][:,torch.as_tensor(ci,device=p.device)].double().cpu().numpy()
        sv=np.linalg.svd(a-a.mean(0),compute_uv=False);observed=float(sv[0]**2/max((sv**2).sum(),1e-30));null=[]
        for _ in range(s['matrix_nulls']):
            b=np.stack([rng.permutation(a[:,j]) for j in range(a.shape[1])],axis=1);ss=np.linalg.svd(b-b.mean(0),compute_uv=False)
            null.append(float(ss[0]**2/max((ss**2).sum(),1e-30)))
        out[name]=dict(shape=list(p.shape),sample_rows=ri.tolist(),sample_cols=ci.tolist(),centered_sample_singular_values=sv.tolist(),
            sample_effective_rank=entropy_rank(sv**2),top_fraction=observed,independent_column_shuffle_top_fraction=null)
    return out


def npz_save(path,arrays):
    path=Path(path);path.parent.mkdir(parents=True,exist_ok=True);tmp=path.with_suffix('.tmp')
    with tmp.open('wb') as f:np.savez_compressed(f,**arrays)
    os.replace(tmp,path)


def npz_read(p):
    with np.load(p,allow_pickle=False) as a:return {k:a[k] for k in a.files}


def save_checkpoint(e,folder,step,s):
    # One rolling checkpoint per seed. Source checkpoints are never modified.
    path=folder/'resume.pt';tmp=folder/'resume.pt.tmp'
    needed=3*e.pb+256*1024**2
    if shutil.disk_usage(folder).free<needed+s['minimum_free_gb']*1024**3:raise Pause('Insufficient reserve for atomic rolling checkpoint; last committed checkpoint remains usable')
    torch.save(dict(engine=e.pack(),step=step,torch_rng=torch.get_rng_state(),cuda_rng=torch.cuda.get_rng_state_all() if torch.cuda.is_available() else []),tmp)
    os.replace(tmp,path)


def restore_seed(e,s,seed):
    folder=Path(s['output'])/f'seed{seed}';folder.mkdir(exist_ok=True)
    cp=folder/'resume.pt'
    if cp.exists():
        z=load(cp);e.restore(z['engine']);step=int(z['step']);torch.set_rng_state(z['torch_rng'])
        if z.get('cuda_rng') and torch.cuda.is_available():torch.cuda.set_rng_state_all(z['cuda_rng'])
    else:
        e.restore(load(Path(s['source'])/f'seed{seed}/anchor.pt'))
        if e.c.transition=='reset':e.reset_optimizer()
        step=0
    return step,folder


def natural_step(e,data,s,seed,step,monitor,ctl):
    start=time.time();ctl.check();ctl.pulse(seed=seed,step=step,phase='monitor task-A gradient')
    mon=[r for r in data['A_valid'] if r['entity'] in monitor]
    ga=mean_gradient(e,mon)
    ctl.pulse(phase='original B minibatch gradient')
    train=e.gradient(minibatches(data,'B',seed,step,e.c));h,c=channels(e)
    before={n:p.detach().cpu().clone() for n,p in e.params.items()}
    records={};sums=dict(h2=0.,c2=0.,hc=0.,g2=0.,g_h=0.,g_c=0.,g_delta=0.,delta2=0.,reconstruction_error2=0.)
    for n,p in e.params.items():
        if n not in h:continue
        a,b,g=h[n],c[n],ga[n]
        rr=dict(group=group(n),shape=list(p.shape),h2=dot(a,a),c2=dot(b,b),hc=dot(a,b),g2=dot(g,g),g_h=dot(g,a),g_c=dot(g,b))
        records[n]=rr
        for k in ['h2','c2','hc','g2','g_h','g_c']:sums[k]+=rr[k]
    curve=None
    if s['curvature_every'] and step%s['curvature_every']==0:
        ctl.check();ctl.pulse(phase='mixed history/current Hessian contraction')
        curve=mixed_curvature(e,mon[:s['curvature_entities']],h,c)
    # Measurement autograd calls above do not touch the clipped .grad used here.
    ctl.check();ctl.pulse(phase='natural Adam update')
    e.opt.step();e.opt.zero_grad(set_to_none=True)
    delta={}
    for n,p in e.params.items():
        d=p.detach().cpu()-before[n];delta[n]=d
        if n not in records:continue
        rr=records[n];rr.update(delta2=dot(d,d),g_delta=dot(ga[n],d),reconstruction_error2=dot(d-h[n]-c[n],d-h[n]-c[n]),
            weight_norm_before=math.sqrt(dot(before[n],before[n])),weight_norm_after=math.sqrt(dot(p.detach(),p.detach())),
            weight_cosine_before_after=cos(before[n],p.detach().cpu()))
        for k in ['delta2','g_delta','reconstruction_error2']:sums[k]+=rr[k]
    group_totals={}
    for rr in records.values():
        g=group_totals.setdefault(rr['group'],{k:0. for k in ['h2','c2','hc','g_h','g_c','delta2','g_delta']})
        for k in g:g[k]+=rr[k]
    sums['history_current_cosine']=sums['hc']/max(math.sqrt(sums['h2']*sums['c2']),1e-30)
    sums['channel_reconstruction_relative_error']=math.sqrt(sums['reconstruction_error2']/max(sums['delta2'],1e-30))
    del h,c,before,ga
    ctl.pulse(phase='all-entity A/B evaluation')
    evaluation=evaluate(e,data,s['eval_batch'])
    if step%s['derivative_every']==0:
        ctl.pulse(phase='post-update monitor gradient')
        post=mean_gradient(e,mon);sums['post_gradient_dot_delta']=sum(dot(post[n],delta[n]) for n in post)
        sums['directional_gradient_change']=sums['post_gradient_dot_delta']-sums['g_delta'];del post
    del delta
    return dict(seed=seed,step=step,evaluation=evaluation,channels=sums,parameter_groups=group_totals,matrices=records,mixed_curvature=curve,
        training=dict(raw_gradient_norm=train['raw_norm'],clip=train['clip'],weight_decay=0),seconds=time.time()-start)


def identity(s):
    x={k:v for k,v in s.items() if k not in ['hours','reserve_minutes','minimum_free_gb','max_measurement_gb','output']}
    return hashlib.sha256(json.dumps(x,sort_keys=True).encode()).hexdigest()


def run(s):
    import fcntl
    out=Path(s['output']);out.mkdir(parents=True,exist_ok=True)
    with (out/'worker.lock').open('a') as lock:
        try:fcntl.flock(lock,fcntl.LOCK_EX|fcntl.LOCK_NB)
        except BlockingIOError:return
        ctl=Control(s);e=None;con=None;folder=None;completed_step=None
        try:
            c=validate(s);monitor,held=split_ids(s,c);con=db_open(out)
            atomic_json(dict(monitor_entities=monitor,heldout_geometry_entities=held,note='Disjoint diagnostic identities, not unseen model-training identities.'),out/'partition.json')
            atomic_json(dict(python=sys.version,torch=torch.__version__,platform=platform.platform(),cuda=torch.version.cuda,
                device=torch.cuda.get_device_name(0) if torch.cuda.is_available() else 'CPU'),out/'hardware.json')
            ctl.pulse(phase='loading original OLMo model')
            e=Engine(c)
            required=(len(s['seeds'])+1)*3*e.pb+s['minimum_free_gb']*1024**3
            if not list(out.glob('seed*/resume.pt')) and shutil.disk_usage(out).free<required:raise Pause(f'Need approximately {required/1024**3:.1f} GiB free for bounded rolling checkpoints plus reserve')
            # Resume positions are cheap JSON mirrors of committed checkpoint steps.
            cursors={seed:read(out/f'seed{seed}/committed.json',{}).get('step',0) for seed in s['seeds']}
            while any(v<s['end_step'] for v in cursors.values()):
                for seed in s['seeds']:
                    if cursors[seed]>=s['end_step']:continue
                    ctl.check();ctl.pulse(seed=seed,phase='loading seed continuation')
                    completed_step,folder=restore_seed(e,s,seed);cursors[seed]=completed_step
                    data=make_data(e.tok,c,seed)
                    if digest(data)!=read(Path(s['source'])/f'seed{seed}/data.json')['hash']:raise ValueError('Source task data hash differs; refusing an incomparable run.')
                    # Remove measurements newer than a durable checkpoint, then deterministically replay.
                    con.execute('DELETE FROM steps WHERE seed=? AND step>?',(seed,completed_step));con.commit()
                    for f in folder.glob('snapshot_*.npz'):
                        if int(f.stem.split('_')[-1])>completed_step:f.unlink()
                    while completed_step<s['start_step']:
                        ctl.check();e.gradient(minibatches(data,'B',seed,completed_step+1,c));e.opt.step();e.opt.zero_grad(set_to_none=True);completed_step+=1
                    anchor=folder/'baseline.npz'
                    if not anchor.exists():
                        ctl.pulse(phase='baseline diagnostics',step=completed_step)
                        arr,meta=capture(e,data,s,monitor,held,ctl);npz_save(anchor,arr);atomic_json(meta,folder/'geometry_entities.json')
                        atomic_json(evaluate(e,data,s['eval_batch']),folder/'baseline_losses.json')
                        save_checkpoint(e,folder,completed_step,s);atomic_json(dict(step=completed_step),folder/'committed.json')
                    base=npz_read(anchor);meta=read(folder/'geometry_entities.json')
                    snaps=sorted(folder.glob('snapshot_*.npz'));previous=npz_read(snaps[-1]) if snaps else base
                    end=min(completed_step+s['chunk_steps'],s['end_step'])
                    for step in range(completed_step+1,end+1):
                        measured_start=time.time()
                        rec=natural_step(e,data,s,seed,step,monitor,ctl)
                        # The natural update is now complete even if an optional diagnostic is interrupted.
                        completed_step=step
                        if step%s['geometry_every']==0:
                            try:
                                arr,meta=capture(e,data,s,monitor,held,ctl)
                                ctl.pulse(phase='topology, frames and sampled matrix spectra')
                                rec['geometry']=geometry_analysis(arr,base,previous,meta,s,seed)
                                rec['sampled_matrix_spectra']=sampled_matrices(e,s,seed)
                                monitor_frames=[]
                                for key in arr:
                                    if key.startswith('A_valid__') and key.endswith('__x'):
                                        prefix=key[:-1]
                                        fm=frame_metrics(arr[key],base[key],arr[prefix+'lossgrad'],base[prefix+'lossgrad'],s['frame_rank'])
                                        angles=fm['principal_angles_degrees']
                                        monitor_frames.append([float(np.mean(angles)) if angles else 0.,fm['mean_shift_norm'],float(np.mean(fm['old_sensitivity_dot_displacement']))])
                                rec['monitor_frame_features']=np.mean(monitor_frames,axis=0).tolist()
                                npz_save(folder/f'snapshot_{step:05d}.npz',arr);previous=arr
                            except Pause as exc:
                                rec['geometry_incomplete']=str(exc)
                                con.execute('INSERT OR REPLACE INTO steps VALUES (?,?,?)',(seed,step,json.dumps(rec,allow_nan=False)));con.commit();raise
                        before_eval=read(folder/'baseline_losses.json') if step==s['start_step']+1 else None
                        if before_eval is None:
                            row=con.execute('SELECT record FROM steps WHERE seed=? AND step=?',(seed,step-1)).fetchone()
                            before_eval=json.loads(row[0])['evaluation'] if row else None
                        if before_eval:
                            prior=[r['loss'] for r in before_eval['A_valid']['rows'] if r['entity'] in monitor]
                            after=[r['loss'] for r in rec['evaluation']['A_valid']['rows'] if r['entity'] in monitor]
                            change=float(np.mean(after)-np.mean(prior));rec['monitor_loss_change']=change;rec['monitor_finite_remainder']=change-rec['channels']['g_delta']
                        rec['total_measurement_seconds']=time.time()-measured_start
                        con.execute('INSERT OR REPLACE INTO steps VALUES (?,?,?)',(seed,step,json.dumps(rec,allow_nan=False)));con.commit()
                        ctl.pulse(phase='step measurements saved',seed=seed,step=step)
                        if step%s['checkpoint_every']==0:
                            save_checkpoint(e,folder,completed_step,s);atomic_json(dict(step=completed_step),folder/'committed.json');ctl.storage()
                        ctl.check()
                    save_checkpoint(e,folder,completed_step,s);atomic_json(dict(step=completed_step),folder/'committed.json');cursors[seed]=completed_step
                    report(out);del base,previous;gc.collect()
            final='complete';message='All configured natural trajectories finished.'
        except Pause as exc:
            final='paused';message=str(exc)
            if e is not None and folder is not None and completed_step is not None:
                try:save_checkpoint(e,folder,completed_step,s);atomic_json(dict(step=completed_step),folder/'committed.json')
                except Pause as save_error:message+='; '+str(save_error)
        except Exception:
            final='failed';message=traceback.format_exc();(out/'error.txt').write_text(message)
            # Do not commit potentially half-measured/half-updated state on unexpected failure.
        finally:
            if con is not None:con.close()
        try:report(out)
        except Exception:(out/'report_error.txt').write_text(traceback.format_exc())
        atomic_json(dict(status=final,message=message,last_progress=time.time()),out/'status.json')
        try:export(out)
        except Exception:(out/'export_error.txt').write_text(traceback.format_exc())


def records(output):
    p=Path(output)/'measurements.sqlite'
    if not p.exists():return []
    with sqlite3.connect(f'file:{p}?mode=ro',uri=True) as con:return [json.loads(r[0]) for r in con.execute('SELECT record FROM steps ORDER BY seed,step')]


def report(output):
    out=Path(output);rr=records(out)
    if not rr:return
    flat=[]
    for r in rr:
        row=dict(seed=r['seed'],step=r['step'],seconds=r['seconds'],**{sp:r['evaluation'][sp]['mean'] for sp in SPLITS},**r['channels'])
        row.update(monitor_loss_change=r.get('monitor_loss_change'),monitor_finite_remainder=r.get('monitor_finite_remainder'))
        flat.append(row)
    fields=sorted(set().union(*(r.keys() for r in flat)))
    with (out/'trajectory.csv').open('w',newline='') as f:
        w=csv.DictWriter(f,fieldnames=fields);w.writeheader();w.writerows(flat)
    lines=['NATURAL TRAJECTORY — unchanged original Adam training','Measurements are observational; diagnostics do not establish a universal cause.']
    for seed in sorted(set(r['seed'] for r in rr)):
        rows=[r for r in rr if r['seed']==seed];last=rows[-1]
        lines.append(f"Seed {seed}: {len(rows)} measured updates; last step {last['step']}; A_test {last['evaluation']['A_test']['mean']:.6f}; B_test {last['evaluation']['B_test']['mean']:.6f}")
        events=sorted([r for r in rows if 'monitor_loss_change' in r],key=lambda r:r['monitor_loss_change'],reverse=True)[:3]
        lines.append('Largest A-monitor increases: '+', '.join(f"step {r['step']}: {r['monitor_loss_change']:+.6f}" for r in events))
    lines += ['Event ranking uses A-valid monitor identities. A-test data are not used to select the events.',
        'All matrix step statistics cover unique named parameters; spectra are coordinate samples, not full matrix spectra.',
        'Hidden sensitivities describe final-token residual sites with other token positions held fixed.',
        'PH is invariant to global rotations/translations. Task semimetric is frozen at baseline; it is not Fisher.',
        'Native Adam history/current channels and QK/gate versus content parameter groups are distinct decompositions.',
        'Only baseline and scheduled last-token activations/sensitivities are retained. Full token arrays and historical checkpoints are not retained.']
    (out/'REPORT.txt').write_text('\n'.join(lines)+'\n')
    import matplotlib
    matplotlib.use('Agg')
    import matplotlib.pyplot as plt
    seeds=sorted(set(r['seed'] for r in rr));fig,axes=plt.subplots(len(seeds),3,figsize=(14,3.3*len(seeds)),squeeze=False)
    for i,seed in enumerate(seeds):
        rows=[r for r in rr if r['seed']==seed];x=[r['step'] for r in rows]
        for sp in ['A_test','B_test']:axes[i,0].plot(x,[r['evaluation'][sp]['mean'] for r in rows],label=sp)
        for field in ['g_h','g_c','g_delta']:axes[i,1].plot(x,[r['channels'][field] for r in rows],label=field)
        axes[i,2].plot(x,[r['channels']['history_current_cosine'] for r in rows],label='history/current cosine')
        for ax in axes[i]:ax.set_xlabel('Natural B update');ax.grid(alpha=.2);ax.legend(fontsize=8)
        axes[i,0].set_ylabel(f'Seed {seed} KL');axes[i,1].set_title('A-monitor first-order projections');axes[i,2].set_ylim(-1.05,1.05)
    fig.tight_layout();fig.savefig(out/'trajectory.png',dpi=160);plt.close(fig)
    # Honest held-out-seed exploratory prediction, no test-set hyperparameter tuning.
    lagged=[]
    for seed in seeds:
        rows=[r for r in rr if r['seed']==seed]
        for prev,nxt in zip(rows,rows[1:]):
            if nxt['step']!=prev['step']+1:continue
            lagged.append(dict(seed=seed,step=prev['step'],x=[math.sqrt(prev['channels']['delta2']),prev['channels']['history_current_cosine'],prev['channels']['g_h'],prev['channels']['g_c']],
                y=nxt['evaluation']['A_test']['mean']-prev['evaluation']['A_test']['mean']))
    scores=[]
    for seed in seeds:
        tr=[r for r in lagged if r['seed']!=seed];te=[r for r in lagged if r['seed']==seed]
        if len(tr)<12 or len(te)<4:continue
        for label,indices in [('update_norm_only',[0]),('norm_and_channels',[0,1,2,3])]:
            x=np.array([r['x'] for r in tr])[:,indices];xt=np.array([r['x'] for r in te])[:,indices];y=np.array([r['y'] for r in tr]);yt=np.array([r['y'] for r in te])
            mu=x.mean(0);sd=np.maximum(x.std(0),1e-12);x=np.c_[np.ones(len(x)),(x-mu)/sd];xt=np.c_[np.ones(len(xt)),(xt-mu)/sd]
            penalty=np.eye(x.shape[1]);penalty[0,0]=0;coef=np.linalg.solve(x.T@x+penalty,x.T@y);pred=xt@coef
            scores.append(dict(heldout_seed=seed,model=label,n=len(te),MSE=float(np.mean((pred-yt)**2)),constant_training_mean_MSE=float(np.mean((yt-y.mean())**2))))
    geometry_scores=[]
    for seed in seeds:
        rows=[r for r in rr if r['seed']==seed];lookup={r['step']:r for r in rows}
        for r in rows:
            nxt=lookup.get(r['step']+1)
            if nxt is None or 'monitor_frame_features' not in r:continue
            geometry_scores.append(dict(seed=seed,x=[math.sqrt(r['channels']['delta2']),r['channels']['history_current_cosine'],r['channels']['g_h'],r['channels']['g_c']]+r['monitor_frame_features'],y=nxt['evaluation']['A_test']['mean']-r['evaluation']['A_test']['mean']))
    gs=[]
    for seed in seeds:
        tr=[r for r in geometry_scores if r['seed']!=seed];te=[r for r in geometry_scores if r['seed']==seed]
        if len(tr)<16 or len(te)<4:continue
        for label,indices in [('norm_only',[0]),('norm_channels',[0,1,2,3]),('norm_channels_frames',list(range(7)))]:
            x=np.array([r['x'] for r in tr])[:,indices];xt=np.array([r['x'] for r in te])[:,indices];y=np.array([r['y'] for r in tr]);yt=np.array([r['y'] for r in te])
            mu=x.mean(0);sd=np.maximum(x.std(0),1e-12);x=np.c_[np.ones(len(x)),(x-mu)/sd];xt=np.c_[np.ones(len(xt)),(xt-mu)/sd];penalty=np.eye(x.shape[1]);penalty[0,0]=0
            coef=np.linalg.solve(x.T@x+penalty,x.T@y)
            gs.append(dict(heldout_seed=seed,model=label,n=len(te),MSE=float(np.mean((xt@coef-yt)**2)),constant_training_mean_MSE=float(np.mean((yt-y.mean())**2))))
    atomic_json(dict(scores=gs,features=['update_norm','history_current_cosine','g_h','g_c','monitor_mean_subspace_angle','monitor_mean_shift_norm','monitor_mean_local_projection'],note='All models compared on the same scheduled geometry points. Features use A-valid monitor identities; next-step target is all-entity A-test loss change. Fixed ridge=1, fit and normalization exclude evaluation seed. No tuning on A-test.'),out/'frame_prediction.json')
    atomic_json(dict(scores=scores,note='Exploratory next-update prediction, ridge penalty fixed at 1; normalization fitted only on other seeds. Few seeds and shared tasks limit inference. Scheduled frame comparisons are in frame_prediction.json.'),out/'lagged_prediction.json')


def export(output):
    out=Path(output);dest=out/'natural_geometry_share.zip';temp=out/'natural_geometry_share.zip.tmp'
    # SQLite backup gives a consistent snapshot even with an active worker.
    db=out/'measurements.sqlite';backup=out/'export_snapshot.sqlite'
    if db.exists():
        with sqlite3.connect(db) as src,sqlite3.connect(backup) as dst:src.backup(dst)
    with zipfile.ZipFile(temp,'w',zipfile.ZIP_DEFLATED,compresslevel=3) as z:
        for p in out.rglob('*'):
            if p.is_file() and p.name not in ['export_snapshot.sqlite'] and p.suffix in ['.json','.csv','.txt','.png']:
                z.write(p,p.relative_to(out))
        if backup.exists():z.write(backup,'measurements.sqlite')
        z.writestr('EXPORT_SCOPE.txt','Raw float32 activation NPZs and model/optimizer checkpoints excluded. SQLite contains all stored scalar, per-entity, matrix and topology measurements.\n')
    os.replace(temp,dest);backup.unlink(missing_ok=True);return str(dest)


def alive(output):
    # Lock ownership, not PID existence, is authoritative (no PID reuse hazard).
    import fcntl
    p=Path(output)/'worker.lock'
    if not p.exists():return False
    with p.open('a') as f:
        try:fcntl.flock(f,fcntl.LOCK_EX|fcntl.LOCK_NB);fcntl.flock(f,fcntl.LOCK_UN);return False
        except BlockingIOError:return True


def status(output):
    out=Path(output);st=read(out/'status.json',{'status':'not_started'});st['alive']=alive(out)
    st['last_progress_age_seconds']=round(max(0,time.time()-st.get('last_progress',time.time())),1)
    st['free_gib']=round(shutil.disk_usage(out if out.exists() else out.parent).free/1024**3,1)
    db=out/'measurements.sqlite';cfg=read(out/'settings.json',{})
    if db.exists() and cfg:
        with sqlite3.connect(f'file:{db}?mode=ro',uri=True) as conn:
            try:st['measured_updates']=conn.execute('SELECT COUNT(*) FROM steps').fetchone()[0]
            except sqlite3.OperationalError:st['measured_updates']=0
            if st['measured_updates']>=8:
                recent=[json.loads(r[0]) for r in conn.execute('SELECT record FROM steps ORDER BY rowid DESC LIMIT 16')]
                timings=[r.get('total_measurement_seconds',r['seconds']) for r in recent]
                left=max(0,len(cfg['seeds'])*(cfg['end_step']-cfg['start_step'])-st['measured_updates'])
                st['rough_remaining_compute_hours']=round(left*float(np.mean(timings))/3600,2)
                st['estimate_note']='Recent measured-step timings; excludes checkpoint/loading overhead. Session pauses at configured time budget even if work remains.'
    st['committed_steps']={p.parent.name:read(p)['step'] for p in out.glob('seed*/committed.json')} if out.exists() else {}
    return st


def refresh(output):
    st=status(output);print(json.dumps(st,indent=2));return st


def launch(s):
    import fcntl
    validate(s);out=Path(s['output']);out.mkdir(parents=True,exist_ok=True)
    with (out/'launch.lock').open('a') as f:
        fcntl.flock(f,fcntl.LOCK_EX)
        if alive(out):print('Already running. Use refresh() to inspect progress.');return str(out)
        old=read(out/'settings.json')
        if old and identity(old)!=identity(s):
            # New settings create a sibling run automatically; never erase old results.
            out=out.with_name(out.name+'_'+time.strftime('%Y%m%d_%H%M%S')+'_'+uuid.uuid4().hex[:4]);out.mkdir();s['output']=str(out)
            print('Settings changed; using a new output directory:',out)
        atomic_json(s,out/'settings.json');(out/'STOP').unlink(missing_ok=True)
        for p in Path(__file__).parent.glob('*.py'):
            target=out/'code'/p.name;target.parent.mkdir(exist_ok=True);shutil.copy2(p,target)
        atomic_json(dict(files={p.name:hashlib.sha256(p.read_bytes()).hexdigest() for p in Path(__file__).parent.glob('*.py')},source_config=read(Path(s['source'])/'config.json')),out/'provenance.json')
        atomic_json(dict(status='launching',last_progress=time.time()),out/'status.json')
        with (out/'worker.log').open('a') as log:
            proc=subprocess.Popen([sys.executable,str(out/'code/natural_geometry.py'),'--worker',str(out/'settings.json')],stdout=log,stderr=subprocess.STDOUT,start_new_session=True)
        atomic_json(dict(pid=proc.pid),out/'process.json')
        # Keep launch lock until worker acquires its lifetime lock or exits.
        for _ in range(100):
            if alive(out) or proc.poll() is not None:break
            time.sleep(.1)
        print('Started/resumed:',out);return str(out)


def stop(output):
    out=Path(output);out.mkdir(parents=True,exist_ok=True);(out/'STOP').touch()
    print('Stop requested. The worker will save at a safe boundary; refresh until alive is false. Do not use restart to resume.')


def restart(s):
    if alive(s['output']):stop(s['output']);print('Wait for the stop to finish, then call restart again.');return None
    out=Path(s['output']);s['output']=str(out.with_name(out.name+'_fresh_'+time.strftime('%Y%m%d_%H%M%S')))
    return launch(s)


def show(output):
    report(output);p=Path(output)/'REPORT.txt'
    print(p.read_text() if p.exists() else 'No completed measured steps yet.')
    try:
        from IPython.display import display,Image
        if (Path(output)/'trajectory.png').exists():display(Image(filename=str(Path(output)/'trajectory.png')))
    except ImportError:pass


if __name__=='__main__':
    parser=argparse.ArgumentParser();parser.add_argument('--worker');a=parser.parse_args()
    if a.worker:run(read(a.worker))
    else:parser.print_help()
